version: '2'

services:
    application:
        container_name: education_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: education_workspace
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: education_php-fpm
        image: framgia/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: education_nginx
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "2020:80"
        links:
            - php-fpm
    data:
        container_name: education_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    data_test:
        container_name: education_data_test
        image: debian
        volumes:
            - .docker/mysql_test:/var/lib/mysql
            - .docker/data_test:/data
    logs:
        container_name: education_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: education_mysql
        image: mysql
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: education
            MYSQL_USER: education
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mysql_test:
        container_name: education_mysql_test
        image: mysql
        volumes_from:
            - data_test
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: education_test
            MYSQL_USER: education
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    redis:
        container_name: education_redis
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data
